### ISSUE TITLE
Presence du node_modules

### ISSUE THREAD

**Issue by JusteLoneWolf** [GalackQSM/Alcatraz#2]
Bonjour
J'ai vu que dans votre README.md vous avez mis le node_module en téléchargement sauf que c'est bien comme pas bien

Car beaucoup de build NPM dépend de l'os (Windows, Debian, Arch .....) mais aussi de l'architecture de l'os (32 bit, 64 bit) et que par exemple si un personne étant sur Linux qui télécharge le node_modules dispo dans le readme cela ne lui servirais a rien car il devras dans tout les cas les build via `npm i` voir faire un `npm rebuild`

De plus le problème venant de l'installation des module viens du package-lock.json il suffit juste de le supprimé et de refaire l'installation via cmd ou powershell

De plus better-sqlite3 on une installation bien différente entre Windows et Linux 

Je pense qu'il serait mieux de rebuild le package.json et le package-lock.json comme il faut.
Aprés vous faîtes ce que vous voulez mais si juste un conseille pour que ça soit plus user friendly

Cordialement

**Comment by GalackQSM** [comment]
Oui éffectivement mes après tout je les es mis pouir facilité l'installation de ceux qui sont sous windows, car moi etant sur windows la plus part me demande comment le configurer depuis que j'ai mis les modules a télécharger les gens ont beaucoup moins de probleme lors de l'installation

**Comment by JusteLoneWolf** [comment]
Je pense qu'il aurait moins de problème en faisant cela, car ca "oblige" au consommateur de télécharger Visual Studio pour télécharger des simples modules alors qu'ils peuvent s'installé sans tous ça mais bon

**Comment by GalackQSM** [comment]
Bah après selon se qu'il ont et il y as des modules ou il faut visual studio sinon ça prend pas en charge l'installation des modules

**Comment by JusteLoneWolf** [comment]
Normalement aucun module on besoin de Visual Studio et de ce que je vois dans votre package.json je vois des module soit inutile soit douteux

comme

"12": "^1.0.2", =>Readme vide et Chinois
"node": "^15.2.0", => inutile si node est dans le PATH
"@spyte-corp/discord.js-remove-on-reaction": "^1.0.5", => faisable très simplement en DJS
"html-entities": "^1.3.1", => inutilisé
"discord.js-commando": "^0.10.0", => inutilisé
"aki-api": "^5.2.0", => inutilisé 

et pleins d'autre module 
Je conseil de refaire votre package.json via CMD ca pourrais regle pas mal de chose

**Comment by GalackQSM** [comment]
après ses un bot qui ne sera jamais fini il est en dévéloppement constent, donc les modules seront utilisé quand je sais pas mes ils le seront ^^

**Comment by JusteLoneWolf** [comment]
Bah le module nommé '12' il peux etre désistallé car il sert juste a faire division  et des addition mais le module contient une erreur 
![image](https://user-images.githubusercontent.com/36123003/99916690-d36da300-2d0b-11eb-9cb2-32aba916e29b.png)
